### ISSUE TITLE
Double JSON.parse leads to error

### ISSUE THREAD

**Issue by AlexSchwabauer** [water-a/electron-valtio#1]
Hi, 
thanks for the helpful library!

I had issues making it work for primitives other than `number`. 
The issue is that a value is `JSON.parse`-d twice.
Once here
https://github.com/water-a/electron-valtio/blob/6924118647e5110af7f03c3be9d3bed3953cee64/src/preload.ts#L20
and here
https://github.com/water-a/electron-valtio/blob/6924118647e5110af7f03c3be9d3bed3953cee64/src/renderer.ts#L9

This actually is ok for numbers, i.e. `JSON.parse(JSON.parse("42")) === 42`, but for objects or strings, this will throw an exception.

I have solved the issue by removing the JSON.parse in the referenced line in the preload script.

Any change that we can get this fixed in the repo?

**Comment by water-a** [comment]
I just removed the parsing in the preload and bumped the version to 0.0.16. If you however find more bugs, feel free to fork the package yourself and use a package locally.

I discourage use of this library because it runs into some performance issues once the state object gets large enough due to stringifying large objects and parsing large strings. Valtio also falls in terms of performance when you have large arrays. This should really only be used for simple state objects.
